<!DOCTYPE html>

<html>
	<head>
		<title>49184091 - PHP Web Apps </title>
		
		<style type="text/css">
			*
			{
				margin: 0;
				font-family: sans-serif;
			}
		</style>
	</head>
	
	<body>
		<p style="text-align: center; margin-top: 50px;">
			<a href="../../task1.php">Task 1</a> | 
			<a href="../../task2.php">Task 2</a> | 
			<a href="../../task3.php">Task 3</a> | 
			<a href="../../task4.php">Task 4</a> | 
			<a href="../../task5.php">Task 5</a> | 
			<a href="../../task6.php">Task 6</a> | 
			<a href="../../task7.php">Task 7</a> | 
			<a href="../../task8.php">Task 8</a> | 
			<a href="../../task9.php">Task 9</a> | 
			<a href="../../task10.php">Task 10</a> | 
			<a href="../task11_1.php">Task 11.1</a> | 
			<a href="index.php">Task 11.2</a>
		</p>
	</body>
</html>